version: "3.7"

services:
  database:
    image: postgres:12.10
    container_name: database
    restart: always
    ports:
      - 5444:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=ignite
      - POSTGRES_DB=rentx
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: app
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on: 
      - database

volumes:
  pgdata:
    driver: local
